image:
  repository: alifattahi/k8s-webapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort  
  port: 3000
  nodePort: 30001


readinessProbe:
  httpGet:
    path: /ready
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /healthy
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  failureThreshold: 3

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
