version: '3.8'

services:
  webapp:
    image: alifattahi/k8s-webapp:latest # to push to dockerhub or nexus artifactory
    build: .
    ports:
      - "3000:3000"
    environment:
      - FIBER_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
