version: '3.8'

services:
  webapp:
    image: alifattahi/k8s-webapp:latest # to push to dockerhub or nexus artifactory
    deploy:
      replicas: 4 # Number of replicas
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    build: .
    expose:
      - 3000
    environment:
      - FIBER_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp

networks:
  default:
    driver: bridge
