apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-webapp-dev
  namespace: argocd
spec:
  project: webapp-project  
  source:
    repoURL: 'https://github.com/alifattahi/k8s-webapp.git'  
    targetRevision: develop
    path: helm/k8s-webapp
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-dev
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
