apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: webapp-project
  namespace: argocd
spec:
  description: My ArgoCD WebApp Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: webapp
      server: https://kubernetes.default.svc
    - namespace: webapp-dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
