apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webapp
spec:
  template:
    spec:
      containers:
        - name: k8s-webapp
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthy
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
