apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-webapp
  template:
    metadata:
      labels:
        app: k8s-webapp
    spec:
      containers:
        - name: k8s-webapp
          image: alifattahi/k8s-webapp:latest
          ports:
            - containerPort: 3000
